language: node_js
node_js:
- '6'
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - npm run selenium:install
  - java -version
  - npm run selenium:start &
  - npm i
  - npm run dev &
  - sleep 10
addons:
  firefox: "52.0"
  apt:
    packages:
      - oracle-java8-installer
      - oracle-java8-set-default
